CREATE TABLE users (
    user_id INT PRIMARY KEY,
    signup_date DATE,
    country VARCHAR(50),
    acquisition_channel VARCHAR(50),
    device_type VARCHAR(20)
);

-- truncate table users

INSERT INTO users
SELECT
    n AS user_id,
    DATE_SUB('2024-06-30', INTERVAL FLOOR(RAND()*540) DAY),

    ELT(FLOOR(1 + RAND()*6),
        'India','USA','UK','Germany','Canada','Australia'),

    ELT(FLOOR(1 + RAND()*5),
        'Organic','Google Ads','Facebook Ads','Referral','LinkedIn Ads'),

    ELT(FLOOR(1 + RAND()*3),
        'Mobile','Desktop','Tablet')

FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 n
    FROM 
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d
) numbers
WHERE n <= 10000;

SELECT COUNT(*) FROM users;
SELECT MIN(signup_date), MAX(signup_date) FROM users;